# Generated by Django 5.1.2 on 2024-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_nutr', '0002_alter_coachnutri_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachnutri',
            name='certifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coachnutri',
            name='specialization',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
