# Generated by Django 5.1.2 on 2024-10-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_nutr', '0003_alter_coachnutri_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachnutri',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/'),
        ),
    ]
