# Generated by Django 5.1.2 on 2024-10-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_nutr', '0004_alter_coachnutri_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachnutri',
            name='profile_picture',
        ),
    ]
