# Generated by Django 5.1.2 on 2024-10-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coach_nutr', '0005_remove_coachnutri_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachnutri',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='coachnutri_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='coachnutri',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='coachnutri_permissions', to='auth.permission'),
        ),
    ]
