# Generated by Django 5.1.2 on 2024-11-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_nutr', '0006_alter_coachnutri_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachnutri',
            name='photo',
            field=models.ImageField(default='profile_photos/default.png', upload_to='profile_photos/'),
        ),
    ]
