# Generated by Django 5.1.2 on 2024-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_nutr', '0007_coachnutri_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachnutri',
            name='photo',
            field=models.TextField(blank=True, default='https://www.shareicon.net/data/256x256/2016/07/21/799323_user_512x512.png', null=True),
        ),
    ]
