# Generated by Django 5.1.2 on 2024-11-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (light exercise/sports 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('active', 'Active (hard exercise/sports 6-7 days a week)'), ('very_active', 'Very active (very hard exercise/sports & a physical job)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.TextField(default='https://e7.pngegg.com/pngimages/946/556/png-clipart-computer-icons-login-user-profile-client-smiley-%D0%B7%D0%BD%D0%B0%D1%87%D0%BA%D0%B8.png'),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
