# Generated by Django 5.1.2 on 2024-11-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_activity_level_client_goal_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='goal_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
